class student:
    subject = "python"
    college = "abc"
    year = "2nd year "
stu1 = student()
stu2 = student()
print(stu1.subject)
print(stu1.college)
print(stu1.year)
print(stu2.subject)
print(stu2.college) 
print(stu2.year)


print(stu1.subject , stu1.college , stu1.year)
print(stu2.subject , stu2.college , stu2.year)


#  
l =[1,2]
s = set()
print(type(l))
print(type(s))


# we can define function by def keyword 
def add(a,b):
    return a+b